spring.application.name=centrol-fee

# ==========================================
# PostgreSQL Database
# ==========================================
server.port=5000
spring.datasource.url=jdbc:postgresql://localhost:5433/central_fee
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# ==========================================
# MyBatis
# ==========================================

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.centrol_fee
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true